# Generated by Django 3.2.7 on 2021-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
