# Generated by Django 3.2.7 on 2021-10-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_auto_20211012_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, default='pizzas/default.jpg', null=True, upload_to='pizzas/'),
        ),
    ]
