# Generated by Django 3.2.7 on 2021-10-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaiolos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzaiolo',
            options={'ordering': ['last_name']},
        ),
        migrations.RenameField(
            model_name='pizzaiolo',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='pizzaiolo',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
